### PR TITLE
Update PKGBUILD to version 1.7 of PhotoQt

### PR DESCRIPTION
**Pull request by luspi**

### CODE REVIEW

**Comment by abucodonosor** [comment]
try with an own update without to copy things from AUR or whoever ..

**Comment by luspi** [comment]
Well, I *am* the maintainer of the AUR package, so, yes, I re-used some bits of my PKGBUILD there.

In fact, I am also the developer of PhotoQt itself, and I received an email from somebody asking how to get the latest version on KaOS, so I thought about how to help with that...

**Comment by abucodonosor** [comment]
Well but the PB is wrong .. not olny while you use not-yet-packged-dependecies as
optdepends=() but the way you use cmake build too.

Also parts seems to link on libqpsd-git ( does not exists here ) but however
everything links on something cannot be optdepends=() , right ?

**Comment by ShalokShalom** [comment]
Thanks for contributing luspi

**Comment by luspi** [comment]
My apologies, something went "wrong", and instead of adding a new commit to this pull request, a new one was created addressing the issues mentioned by @abucodonosor: #3

**Pull request closed without merging**
