### PR TITLE
 fix PKGBUILD, verified on KaOS (VirtualBox) 

### PR DESCRIPTION
**Pull request by luspi**
Successfully builds latest version of PhotoQt on KaOS (verified)

### CODE REVIEW

**Comment by luspi** [comment]
(Sorry, meant to add this on to the already existing pull request)

**Comment by luspi** [comment]
I installed KaOS (in VirtualBox), fixed the cmake usage (went back to how the old PKGBUILD did it) and disabled the non-existant poppler-qt5 dependency. It now builds successfully on KaOS!

**Comment by luspi** [comment]
Just as an fyi, since it was mentioned in the other pull request, the libqpsd dependency is not a compile time dependency, nothing links against that...

**Comment by abucodonosor** [comment]
@luspi 

poppler-qt5 is just poppler on KaOS also libqpsd* does not exists on KaOS.

If you wish libqpsd dependecie you need to package that too or remove it.

**Comment by ShalokShalom** [comment]
ln KaOS, a lot of stuff is packaged as upstream ships it, so nearly no split happens in the packages here.

In order to find such sub-packages, you can use 
```
pkgfile -vri filename
```

This works on Arch too

Update that list via pkgfile -u initially and constantly 

Happy hacking and thanks a lot

**Comment by luspi** [comment]
@abucodonosor 
Got it, thanks! I removed the optdepends altogether (both libqpsd and the one that was already there) as neither has a package in KaOS.

@ShalokShalom 
That makes sense! Thanks for the tip with pkgfile, didn't know that one yet...


(Btw, KaOS looks very nice! This was the first time I installed it locally, and I'll probably play around with it a little more...)

**Pull request merged**
